version: '3.9'

services:
  mysql:
    platform: linux/amd64
    image: mysql:8
    container_name: demodb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=demodb
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "demodb" ]
      timeout: 20s
      retries: 10

  walletapp:
    container_name: walletapp
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    image: walletapp:latest
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=demodb

#version: '3.3'
#services:
#  db:
#    image: mysql:5.7
#    platform: linux/amd64
#    restart: always
#    container_name: barakadb
#    environment:
#      MYSQL_DATABASE: 'db'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'user123'
#      MYSQL_ROOT_PASSWORD: 'user123'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - my-db:/var/lib/mysql
#
#  walletapp:
#    container_name: walletapp
#    platform: linux/amd64
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: walletapp:latest
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#volumes:
#  my-db: